from SubstitutionCipher import *



#mensaje="LAR ZPUHTFTY XWEUPJR GHGZT"
#mensaje="PVREK BIG QF. JCDQZRF' ZNVEFH OBCX: 'C BEWRS VVUTBFL BT BKNX CVAY BKNX CVAY BKNX'"
#mensaje="ZHOFRPH WR JUDYLWB IDOOV. QHAW ZHHN: UHWXUQ WR EXWW LVODQG RQZDUGV DRVKLPD!"
#mensaje = "PU. FDHVDULDQ ZLOO EH RXW QHAW ZHHN. PU. DWEDVK ZLOO VXEVWLWXWH."
#mensaje = "FDUOD, ZKB ZRQW BRX FDOO PH?"
mensaje = "ZHOFRPH WR JUDYLWB IDOOV"

#mensaje = "PYOL YS QH LLFDJW: VAH DNCVFW ZTCKW XKG WFFWWKNLLMRP? WISAGCXJ AR WKUISW! DPX WDSUKXR: LLH UBFO"
#mensaje="LAR ZPUHTFTY XWEUPJR GHGZT"
#mensaje = "PVREK BIG QF. JCDQZRF' ZNVEFH OBCX: 'C BEWRS VVUTBFL BT BKNX CVAY BKNX CVAY BKNX'"        
#mensaje="LAR ZPUHTFTY XWEUPJR GHGZT - PVREK BIG QF. JCDQZRF' ZNVEFH OBCX: 'C BEWRS VVUTBFL BT BKNX CVAY - PYOL YS QH LLFDJW: VAH DNCVFW ZTCKW XKG WFFWWKNLLMRP? WISAGCXJ AR WKUISW! DPX WDSUKXR: LLH UBFO"
 

attacker = SubstitutionCipher()
attacker.load(mensaje)
attacker.showMessages()
while not attacker.exit:
    attacker.accept()