#!/usr/bin/python

from Driver import *



#message="LAR ZPUHTFTY XWEUPJR GHGZT"
#message="PVREK BIG QF. JCDQZRF' ZNVEFH OBCX: 'C BEWRS VVUTBFL BT BKNX CVAY BKNX CVAY BKNX'"
#message="ZHOFRPH WR JUDYLWB IDOOV. QHAW ZHHN: UHWXUQ WR EXWW LVODQG RQZDUGV DRVKLPD!"
message = "PU. FDHVDULDQ ZLOO EH RXW QHAW ZHHN. PU. DWEDVK ZLOO VXEVWLWXWH."
#message = "FDUOD, ZKB ZRQW BRX FDOO PH?"
#message = "ZHOFRPH WR JUDYLWB IDOOV"

#message = "PYOL YS QH LLFDJW: VAH DNCVFW ZTCKW XKG WFFWWKNLLMRP? WISAGCXJ AR WKUISW! DPX WDSUKXR: LLH UBFO"
#message="LAR ZPUHTFTY XWEUPJR GHGZT"
#message = "PVREK BIG QF. JCDQZRF' ZNVEFH OBCX: 'C BEWRS VVUTBFL BT BKNX CVAY BKNX CVAY BKNX'"        
#message="LAR ZPUHTFTY XWEUPJR GHGZT - PVREK BIG QF. JCDQZRF' ZNVEFH OBCX: 'C BEWRS VVUTBFL BT BKNX CVAY - PYOL YS QH LLFDJW: VAH DNCVFW ZTCKW XKG WFFWWKNLLMRP? WISAGCXJ AR WKUISW! DPX WDSUKXR: LLH UBFO"
 

driver = Driver()
driver.load(message)
#driver.showMessages()
while driver.accept():
  pass